name: demo

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo "helloworld !!!"
    - uses: actions/checkout@main
    - uses: azure/login@v1
      with:
        creds:${{ secrets.AZURE_CREDENTIALS }}

    





