name: demo

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo "helloworld !!!"
    - uses: actions/ckeckout@main
    - run: ls                                                                   

      

